/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestigationIndexRouteImport } from './routes/investigation.index'
import { Route as InvestigationFirIdRouteImport } from './routes/investigation.$firId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationIndexRoute = InvestigationIndexRouteImport.update({
  id: '/investigation/',
  path: '/investigation/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationFirIdRoute = InvestigationFirIdRouteImport.update({
  id: '/investigation/$firId',
  path: '/investigation/$firId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/investigation/$firId': typeof InvestigationFirIdRoute
  '/investigation/': typeof InvestigationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/investigation/$firId': typeof InvestigationFirIdRoute
  '/investigation': typeof InvestigationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/investigation/$firId': typeof InvestigationFirIdRoute
  '/investigation/': typeof InvestigationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/analytics'
    | '/assistant'
    | '/forgot-password'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/predictions'
    | '/reports'
    | '/settings'
    | '/investigation/$firId'
    | '/investigation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/analytics'
    | '/assistant'
    | '/forgot-password'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/predictions'
    | '/reports'
    | '/settings'
    | '/investigation/$firId'
    | '/investigation'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/analytics'
    | '/assistant'
    | '/forgot-password'
    | '/intelligence'
    | '/login'
    | '/map'
    | '/predictions'
    | '/reports'
    | '/settings'
    | '/investigation/$firId'
    | '/investigation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PredictionsRoute: typeof PredictionsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  InvestigationFirIdRoute: typeof InvestigationFirIdRoute
  InvestigationIndexRoute: typeof InvestigationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/': {
      id: '/investigation/'
      path: '/investigation'
      fullPath: '/investigation/'
      preLoaderRoute: typeof InvestigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/$firId': {
      id: '/investigation/$firId'
      path: '/investigation/$firId'
      fullPath: '/investigation/$firId'
      preLoaderRoute: typeof InvestigationFirIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PredictionsRoute: PredictionsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  InvestigationFirIdRoute: InvestigationFirIdRoute,
  InvestigationIndexRoute: InvestigationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
